In [1]:
!pip install psycopg2
!pip install pandas

Requirement already satisfied: psycopg2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.9.12)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import psycopg2
import pandas as pd

In [3]:
DB_HOST = "127.0.0.1"      
DB_PORT = "5432"          
DB_NAME = "amazon_sales"  
DB_USER = "postgres"      
DB_PASS = "your_pass"

In [4]:
import psycopg2
from psycopg2 import sql


def create_database(DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS):

    # Connect to PostgreSQL default database
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname="postgres",
        user=DB_USER,
        password=DB_PASS
    )

    conn.set_session(autocommit=True)
    cur = conn.cursor()

    try:
        # Drop database if it already exists
        cur.execute(f"DROP DATABASE IF EXISTS {DB_NAME}")

        # Create new database
        cur.execute(f"CREATE DATABASE {DB_NAME}")

    except psycopg2.Error as e:
        print("Error while creating database:")
        print("Use only '_' as a special character")
        print(e)

    finally:
        cur.close()
        conn.close()

    # Connect to the newly created database
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASS
    )

    cur = conn.cursor()

    return cur, conn

In [5]:
def drop_table(cur, conn):
    for query in drop_table_queries:
        cur.execute(query)
        conn.commit()

In [6]:
def create_table(cur, conn):
    for query in create_table_queries:
        cur.execute(query)
        conn.commit()

In [7]:
try:
    sales = pd.read_csv("enter the file path")
except: 
    print('enter the file path')

In [8]:
sales.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [9]:
sales['category'].unique()

<StringArray>
[                                      'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
                                             'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters',
                                                          'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables',
                                                           'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions',
                                                             'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls',
                                                        'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions',
                            'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts',
                                                           'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables',
                                                             'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts',
                                                       'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables',
 ...
                              'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories',
                                           'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons',
                                            'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|StovetopEspressoPots',
                          'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons',
                                                   'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses',
                                                   'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers',
                                          'Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories',
                                                  'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers',
                                                               'Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans',
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags']
Length: 211, dtype: str

In [10]:
sales['category_id'] = sales['category'].factorize()[0]+1

In [11]:
sales['price_id'] = sales['actual_price'].factorize()[0]+1

In [12]:
products = sales[['product_id', 'product_name', 'category_id', 'about_product', 'img_link', 'product_link']]
products.head()

,product_id,product_name,category_id,about_product,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,1,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,1,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,1,【 Fast Charger& Data Sync】-With built-in safet...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,1,The boAt Deuce USB 300 2 in 1 cable is compati...,https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,1,[CHARGE & SYNC FUNCTION]- This cable comes wit...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [13]:
product_categories = sales[['category_id','category']]
product_categories.head()

   category_id                                           category
0            1  Computers&Accessories|Accessories&Peripherals|...
1            1  Computers&Accessories|Accessories&Peripherals|...
2            1  Computers&Accessories|Accessories&Peripherals|...
3            1  Computers&Accessories|Accessories&Peripherals|...
4            1  Computers&Accessories|Accessories&Peripherals|...

In [14]:
customers = sales[['user_id','user_name']]
customers.head()

,user_id,user_name
0,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp..."
1,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac..."
2,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal..."
3,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ..."
4,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK..."

In [15]:
reviews = sales[['review_id','product_id','user_id','review_title','review_content','rating','rating_count']]
reviews.head()

,review_id,product_id,user_id,review_title,review_content,rating,rating_count
0,"R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...",B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,4.2,"24,269"
1,"RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...",B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,4.0,"43,994"
2,"R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...",B096MSW6CT,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",3.9,"7,928"
3,"R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...",B08HDJ86NZ,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",4.2,"94,363"
4,"R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...",B08CF3B7N1,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",4.2,"16,905"

In [16]:
product_prices = sales[['price_id', 'product_id', 'actual_price', 'discounted_price', 'discount_percentage']]
product_prices.head()

   price_id  product_id actual_price discounted_price discount_percentage
0         1  B07JW9H4J1       ₹1,099             ₹399                 64%
1         2  B098NS6PVG         ₹349             ₹199                 43%
2         3  B096MSW6CT       ₹1,899             ₹199                 90%
3         4  B08HDJ86NZ         ₹699             ₹329                 53%
4         5  B08CF3B7N1         ₹399             ₹154                 61%

In [17]:
cur, conn = create_database(DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS)

Error while creating database:
Use only '_' as a special character
database "amazon_sales" is being accessed by other users
DETAIL:  There is 1 other session using the database.

In [18]:
product_categories_create = ("""
    CREATE TABLE IF NOT EXISTS product_categories(
    category_id INT,
    category_name VARCHAR
    );
    """)

In [19]:
cur.execute(product_categories_create)
conn.commit()

In [20]:
customers_create = ("""
    CREATE TABLE IF NOT EXISTS customers (
    user_id VARCHAR,
    user_name VARCHAR
    );
""")

In [21]:
cur.execute(customers_create)
conn.commit()

In [22]:
products_create = ("""
    CREATE TABLE IF NOT EXISTS products(
    product_id VARCHAR,
    product_name VARCHAR,
    category_id INT NOT NULL,
    about_product VARCHAR,
    img_link VARCHAR,
    product_link VARCHAR
);
""")

In [23]:
cur.execute(products_create)
conn.commit()

In [24]:
product_prices_create = ("""
CREATE TABLE IF NOT EXISTS product_prices (
    price_id INT,
    product_id VARCHAR NOT NULL,
    actual_price VARCHAR NOT NULL,
    discounted_price VARCHAR NOT NULL,
    discount_percentage VARCHAR NOT NULL
);
""")

In [25]:
cur.execute(product_prices_create)
conn.commit()

In [26]:
reviews_create = ("""
CREATE TABLE IF NOT EXISTS reviews (
    review_id VARCHAR,
    product_id VARCHAR NOT NULL,
    user_id VARCHAR NOT NULL,
    review_title VARCHAR,
    review_content VARCHAR,
    rating VARCHAR,
    rating_count VARCHAR
);
""")

In [27]:
cur.execute(reviews_create)
conn.commit()

In [28]:
product_categories_insert = ("""
    INSERT INTO product_categories(
    category_id, category_name)
    VALUES 
    (%s, %s)""")

In [29]:
for i, row in product_categories.iterrows():
    cur.execute(product_categories_insert, list(row))
    conn.commit()

In [30]:
customers_insert = ("""
    INSERT INTO customers(
    user_id, user_name)
    VALUES 
    (%s, %s)""")

In [31]:
for i, row in customers.iterrows():
    cur.execute(customers_insert, list(row))
    conn.commit()

In [32]:
products_insert = ("""
    INSERT INTO products(
    product_id, product_name, category_id, about_product, img_link, product_link)
    VALUES 
    (%s, %s, %s, %s, %s, %s)""")

In [33]:
for i, row in products.iterrows():
    cur.execute(products_insert, list(row))
    conn.commit()

In [34]:
product_prices_insert = ("""
    INSERT INTO product_prices(
    price_id, product_id, actual_price, discounted_price, discount_percentage)
    VALUES 
    (%s, %s, %s, %s, %s)""")

In [35]:
for i, row in product_prices.iterrows():
    cur.execute(product_prices_insert, list(row))
    conn.commit()

In [36]:
reviews_insert = ("""
    INSERT INTO reviews(
    review_id, product_id, user_id, review_title, review_content, rating, rating_count)
    VALUES 
    (%s, %s, %s, %s, %s, %s, %s)""")

In [37]:
for i, row in reviews.iterrows():
    cur.execute(reviews_insert, list(row))
    conn.commit()

In [40]:
display_product_categories = ("""
    SELECT * FROM product_categories;
    """)

In [46]:
cur.execute(display_product_categories)

row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(6, 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(6, 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions')
(7, 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(6, 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(8, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(9, 'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(10, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(11, 'Electronics|HomeTheater,TV&Video|Projectors')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(10, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(2, 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(10, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables')
(6, 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(11, 'Electronics|HomeTheater,TV&Video|Projectors')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(6, 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(12, 'Electronics|HomeAudio|Accessories|Adapters')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(7, 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(13, 'Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(3, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(14, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|DVICables')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(4, 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(15, 'Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(7, 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(5, 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')
(1, 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables')

In [47]:
cur.close()
conn.close()